project:
  type: book

book:
  title: "Programación 1"
  subtitle: "Ciclo de Formación Técnica - Estadística y Ciencia de Datos"
  author: 
    - "Marcos Prunello"
    - "Continuar"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - capitulos/00_info.qmd
    - part: capitulos/01.qmd
      chapters:
        - capitulos/01_a_algo.qmd
        - capitulos/01_b_algo.qmd
        - capitulos/01_practica.qmd
    - part: capitulos/02.qmd
      chapters:
        - capitulos/02_a_algo.qmd
  #       - capitulos/02_b_algo.qmd
  #       - capitulos/02_practica.qmd
  # appendices:
  #   - capitulos/98_tp.qmd
  #   - capitulos/99_bibliografia.qmd
  #   - capitulos/01_practica_resuelta.qmd
  #   - capitulos/02_practica_resuelta.qmd
    
lang: es

bibliography: capitulos/references.bib

format:
  html:
    theme:
      light: [cosmo, estilo/style.estilo]
      dark: [darkly, estilo/style-dark.estilo]
    code-link: true
    lightbox: 
      match: auto
      loop: false
    fig-dpi: 300
    fig-show: hold
    fig-align: center
  pdf:
    documentclass: scrbook
    latex-output-dir: _book
    output-file: "programacion1"
    keep-tex: false
    colorlinks: true
    include-in-header: estilo/preambulo.tex
    include-before-body: estilo/cuerpo.tex
    template-partials:
      - estilo/title.tex
    
