project:
  type: book

book:
  title: "Programación 1"
  subtitle: "Ciclo de Formación Técnica - Estadística y Ciencia de Datos"
  author: 
    - "Marcos Prunello"
    - "Continuar"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - 00_info.qmd
    - part: 01.qmd
      chapters:
        - 01_a_algo.qmd
        - 01_b_algo.qmd
        - 01_practica.qmd
    - part: 02.qmd
      chapters:
        - 02_a_algo.qmd
        - 02_b_algo.qmd
        - 02_practica.qmd
    - 98_tp.qmd
    - 99_bibliografia.qmd
  appendices:
    - 01_practica_resuelta.qmd
    - 02_practica_resuelta.qmd
    
lang: es

bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo, scss/style.scss]
      dark: [darkly, scss/style-dark.scss]
    code-link: true
    lightbox: 
      match: auto
      loop: false
    fig-dpi: 300
    fig-show: hold
    fig-align: center
  # pdf:
  #   documentclass: scrreprt
