project:
  type: book

book:
  title: "Programación 1"
  subtitle: "Ciclo de Formación Técnica - Estadística y Ciencia de Datos"
  author: 
    - "Mgs. Lic. Marcos Prunello"
    - "Tec. Cesar Mignoni"
    - "Lic. Gino Bartolelli"
    - "Lic. Iván Millanes"
    - "Dr. Luciano Anselmino"
    - "Lic. Dolores Sollberger"
    - "Julián L'Heureux"
  date: today
  date-format: long
  search: true
  repo-url: https://github.com/ee-unr/programacion-1
  repo-actions: [edit, issue, source]
  downloads: [pdf]
  page-footer: "Developed by Marcos Prunello"
  back-to-top-navigation: true
  chapters:
    - index.qmd
    - capitulos/00_info.qmd
    - part: capitulos/01.qmd
      chapters:
        - capitulos/01_a_intro.qmd
        - capitulos/01_b_primeros_pasos.qmd
        - capitulos/01_c_objetos.qmd
        - capitulos/01_d_operadores.qmd
        - capitulos/01_e_organizacion.qmd
        - capitulos/01_f_errores_estilo_paquetes.qmd
        - capitulos/01_g_opcional.qmd
        - capitulos/01_practica.qmd
    - part: capitulos/02.qmd
      chapters:
        - capitulos/02_1_if.qmd
        - capitulos/02_2_for_while.qmd
        - capitulos/02_practica.qmd
    - part: capitulos/03.qmd
      chapters:
        - capitulos/03_1_crear_funciones.qmd
        - capitulos/03_2_ambito.qmd
        - capitulos/03_3_varios.qmd
        # - capitulos/03_practica.qmd
    - part: capitulos/90.qmd
      chapters:
        - capitulos/90_soluciones_01.qmd
        - capitulos/90_soluciones_02.qmd
        # - capitulos/90_soluciones_03.qmd
  appendices:
  #   - capitulos/98_tp.qmd
    - capitulos/99_bibliografia.qmd

lang: es

format:
  html:
    theme:
      light: [cosmo, estilo/style.scss]
      dark: [darkly, estilo/style-dark.scss]
    css: webexercises/webex.css
    include-after-body: webexercises/webex.js
    code-link: true
    lightbox:
      match: auto
      loop: false
    fig-dpi: 300
    fig-show: hold
    fig-align: center
  pdf:
    documentclass: scrbook
    latex-output-dir: _book
    output-file: "programacion1"
    keep-tex: false
    colorlinks: true
    include-in-header: estilo/preambulo.tex
    include-before-body: estilo/cuerpo.tex
    template-partials:
      - estilo/title.tex