```{=latex}
\thispagestyle{primerapagina}
```

# Paquetes

::: {.presentacion-capitulo data-latex=""}
En este capítulo exploraremos el sistema de paquetes en R, una de sus características más poderosas. Veremos cómo R está compuesto por una base fundamental y un ecosistema de paquetes adicionales que amplían sus funcionalidades. Aprenderemos a instalar y cargar paquetes.
:::

## Diseño del sistema R

R está diseñado como un sistema modular, dividido en dos partes principales:  

- **R Base**: Se instala automáticamente cuando descargamos R desde [CRAN](https://cran.r-project.org) (Comprehensive R Archive Network). Incluye las funciones fundamentales del lenguaje, como operadores matemáticos, herramientas para manipular datos y funciones estadísticas básicas.  

- **Paquetes adicionales**: Son extensiones opcionales que amplían las funcionalidades de R. Cada paquete es un conjunto de funciones y datos diseñados para tareas específicas, como visualización de datos, modelado estadístico o manipulación avanzada de estructuras de datos.  

## Instalación de paquetes  

Para utilizar un paquete en R, primero debemos instalarlo. La mayoría de los paquetes están disponibles en CRAN y, teniendo conexión a internet, se pueden descargar directamente con el siguiente comando:  

```r
install.packages("nombre-del-paquete")
```  

Esto descargará e instalará el paquete en la computadora, permitiéndolo usarlo en futuras sesiones.

## Carga de paquetes  

Después de instalar un paquete, es necesario **cargarlo en la sesión de R** para poder utilizar sus funciones. Es como abrirlo para sacar las funciones que están guardadas dentro. Para hacerlo, usamos la función `library()`:  

```r
library("nombre-del-paquete")
```  
Si intentás usar una función de un paquete sin haberlo cargado previamente, R mostrará un error indicando que el objeto no fue encontrado.  

Es importante recordar que **la instalación de un paquete solo se hace una vez**, pero **debemos cargarlo en cada nueva sesión de R** en la que queramos utilizarlo. Cuando cerramos RStudio, los paquetes se descargan de la memoria, por lo que es necesario volver a llamarlos con `library()` la próxima vez que los necesitemos.  

Este sistema modular permite que R sea altamente flexible, permitiendo a los usuarios instalar solo las herramientas que realmente necesitan para sus análisis.  

## Creación de paquetes en R  

Los paquetes en R no solo son desarrollados por expertos en estadística y computación, sino también por cualquier persona que quiera compartir herramientas útiles con la comunidad. Investigadores, analistas de datos y programadores contribuyen a la expansión del ecosistema de R creando paquetes que facilitan tareas específicas.  

Si bien algunos paquetes pueden ser muy sofisticados, la creación de uno no es algo exclusivo de grandes desarrolladores. De hecho, al finalizar esta materia, contarás con los conocimientos necesarios para construir tu propio paquete desde cero. Esto te permitirá organizar y compartir funciones de manera eficiente, facilitando su reutilización en distintos proyectos.

## Paquetes utilizados en esta materia

Como estaremos aprendiendo nociones de programación, no necesitaremos usar paquetes adicionales en el contexto de esta asignatura, pero sí usarás muchos en otras materias.
