---
number-sections: false
---

```{=latex}
\thispagestyle{primerapagina}
```

# Soluciones de la Práctica de la Unidad 6

Los materiales con las soluciones se encuentran [en este repositorio *online*](https://github.com/ee-unr/programacion-1/tree/main/paquetes_unidad_6). El mismo cuenta con un directorio para cada ejercicio, con los elementos que componen a cada uno de los paquetes que se deben desarrollar. Al explorar las soluciones propuestas, se deben tener en cuenta los siguientes comentarios:

- El código de las funciones está en el subdirectorio `R`.
- La carpeta `man` contiene archivos para la generación de páginas de ayuda, creados automáticamente a partir de la documentación de las funciones (no se edita a mano).
- El archivo `DESCRIPTION` debe ser editado a mano.
- El archivo `NAMESPACE` no debe ser editado a mano, sino que es modificado automáticamente a partir de la documentación de las funciones.
- Se ha omitido el archivo 
- Estos paquetes son extremadamente sencillos y contienen lo mínimo e indispensable para su funcionamiento. Un desarrollo más profesional debe incluir otros aspectos, como los mencionados en el material de lectura opcional.
- En estos directorios no se incluyeron otros archivos que son creados automáticamente por `devtools` al crear el paquete: el archivo de configuración del proyecto (extensión `.Rproj`), la carpeta `.Rproj.user` y los archivos `.gitignore` y `.Rbuildignore`. Estos componentes no son de interés para los ejemplos básicos desarrollados.
